/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import javax.swing.ImageIcon;

/**
 *
 * @author ahmedmaawy
 */
public class PermissionsPanel extends javax.swing.JPanel {

    private boolean usageYes = false;
    private boolean turnedOnYes = false;
    
    private ImageIcon yesNoNoIcon;
    private ImageIcon yesNoYesIcon;
    
    /**
     * Creates new form PermissionsPanel
     */
    public PermissionsPanel() {
        initComponents();
        
        yesNoNoIcon = new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"));
        yesNoYesIcon = new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoYes.png"));
    }
    
    /**
     * The usage toggle status
     * 
     * @return 
     */

    public boolean isUsageYes() {
        return usageYes;
    }
    
    /**
     * The turned on toggle status
     * 
     * @return 
     */

    public boolean isTurnedOnYes() {
        return turnedOnYes;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPermissionsTop = new javax.swing.JPanel();
        jLabelLiveEditing = new javax.swing.JLabel();
        jPanelPermissionsBottom = new javax.swing.JPanel();
        jLabelRecordInfo = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        checkUsage = new javax.swing.JCheckBox();
        checkRegister = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jPanelPermissionsTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPermissionsTop.setOpaque(false);

        jLabelLiveEditing.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelLiveEditing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLiveEditing.setText("Can we record your use of OpenSIMKit?");

        org.jdesktop.layout.GroupLayout jPanelPermissionsTopLayout = new org.jdesktop.layout.GroupLayout(jPanelPermissionsTop);
        jPanelPermissionsTop.setLayout(jPanelPermissionsTopLayout);
        jPanelPermissionsTopLayout.setHorizontalGroup(
            jPanelPermissionsTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsTopLayout.createSequentialGroup()
                .add(jLabelLiveEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPermissionsTopLayout.setVerticalGroup(
            jPanelPermissionsTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsTopLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelLiveEditing)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPermissionsBottom.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPermissionsBottom.setOpaque(false);

        jLabelRecordInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelRecordInfo.setText("<html><div style=\"width:100%\"><center><p>Recording how often and where SIMKit is used is important in ensuring that this software remains free for all to use</p></center></div></html>");

        jButtonContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/ContinueButton.png"))); // NOI18N
        jButtonContinue.setBorderPainted(false);
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        checkUsage.setText("<html><div style=\"width:100%\"><p>Allow SIMKit to collect anonymous data about the way you use this app (not including the messages you write)</p></div></html>");
        checkUsage.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkUsage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"))); // NOI18N
        checkUsage.setIconTextGap(15);
        checkUsage.setName("checkAllowUsage"); // NOI18N
        checkUsage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkUsageItemStateChanged(evt);
            }
        });

        checkRegister.setText("<html><div style=\"width:100%\"><p>Allow SIMKit to register that this app was turned on (collecting this very basic usage data helps us keep SIMKit free, please keep this in mind before unchecking this option)</p></div></html>");
        checkRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"))); // NOI18N
        checkRegister.setIconTextGap(15);
        checkRegister.setName("checkAllowReg"); // NOI18N
        checkRegister.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkRegisterItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPermissionsBottomLayout = new org.jdesktop.layout.GroupLayout(jPanelPermissionsBottom);
        jPanelPermissionsBottom.setLayout(jPanelPermissionsBottomLayout);
        jPanelPermissionsBottomLayout.setHorizontalGroup(
            jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(checkUsage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 611, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                            .add(80, 80, 80)
                            .add(jLabelRecordInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 524, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                            .add(32, 32, 32)
                            .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                                    .add(384, 384, 384)
                                    .add(jButtonContinue))
                                .add(checkRegister, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 611, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(0, 60, Short.MAX_VALUE))
        );
        jPanelPermissionsBottomLayout.setVerticalGroup(
            jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelRecordInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(checkUsage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(checkRegister, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(jButtonContinue)
                .add(88, 88, 88))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPermissionsBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPermissionsTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelPermissionsTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelPermissionsBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        // TODO add your handling code here:
        OpenSIMKit.anonymousDataCollection.saveXMLSettings(usageYes, turnedOnYes);
        OpenSIMKit.mainFrame.setDisconnectedInterface();
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void checkRegisterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRegisterItemStateChanged
        
        checkRegister.setIcon((evt.getStateChange() == evt.SELECTED) ? yesNoYesIcon : yesNoNoIcon);
    }//GEN-LAST:event_checkRegisterItemStateChanged

    private void checkUsageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkUsageItemStateChanged
        turnedOnYes = (evt.getStateChange() == evt.SELECTED);
        checkUsage.setIcon(turnedOnYes ? yesNoYesIcon : yesNoNoIcon);
    }//GEN-LAST:event_checkUsageItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkRegister;
    private javax.swing.JCheckBox checkUsage;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabelLiveEditing;
    private javax.swing.JLabel jLabelRecordInfo;
    private javax.swing.JPanel jPanelPermissionsBottom;
    private javax.swing.JPanel jPanelPermissionsTop;
    // End of variables declaration//GEN-END:variables
}
